# Group 通用接口

## 获取卡片列表 [GET /cards.do{?type,page,per_page}]

+ Parameters
    + type: product (string, required) - 卡片类型
    + page: 2 (number, required) - 第几页
    + per_page: 20 (number, required) - 页数

+ Response 200 (application/json;charset=utf-8)
    <!--  include(data/cards.json5) -->


## 获取卡片列表222 [GET /cards22.do{?type,page,per_page}]

+ Parameters
    + type: product (string, required) - 卡片类型
    + page: 2 (number, required) - 第几页
    + per_page: 20 (number, required) - 页数

+ Response 200 (application/json;charset=utf-8)
    <!-- include(data/cards2.json5) -->


                