Format: 1A
BaseUri: /pk/znpk



# 智能排课 API 文档

API 前缀为 `/pk/znpk`


# Group 接口约定

:::note

- 定义如下基础参数，并在每个请求 (GET, POST, PUT, DELETE) 地址中带上：

  - `schemeId`： 排课方案Id
  - `gradeId`： 年级Id
  - `campus`： 校区Id
:::


