# Group 通用接口

## 获取班级列表 [GET /classes.do]

+ Response 200 (application/json;charset=utf-8)
  <!-- include(data/classes.json5) -->


## 获取排课节次 [GET /lesson_times.do{?classId}]

+ Parameters
    + classId: class01 (string, required) - 班级id

+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + success: true (boolean, required) - 是否处理成功
        + message: `处理消息` (string, required) - 是否处理成功
        + data (object)
            + days: 5 (number, required) - 一周几天
            + dayLessons: 10 (number, required) - 一天几节次

    



